"use strict";

const assert = require("node:assert/strict");
const apps = require("../site/assets/skill-apps.js");
const progress = require("../site/assets/skill-progress.js");

const data = {
  domains: [
    { id: "a", name: "Domain A, Full Canonical Name" },
    { id: "b", name: "Domain B & Full Canonical Name" },
    { id: "c", name: "Domain C, Full Canonical Name" },
  ],
  values: [
    { id: "x", name: "Value X", definition: "", aliases: [] },
    { id: "shared", name: "Shared Value", definition: "", aliases: [] },
    { id: "unassigned", name: "Unassigned Value", definition: "", aliases: [] },
  ],
};
const custom = { id: "custom-1", name: "My custom Value", definition: "Mine", aliases: [] };
const state = {
  step: 4,
  furthestStep: 5,
  selectedDomains: ["a", "b", "c"],
  domainImportance: { a: "High", b: "High", c: "High" },
  assessments: {
    a: { current: 2, desired: 8 },
    b: { current: 3, desired: 6 },
    c: { current: 5, desired: 6 },
  },
  selected: {
    x: { rating: "High" },
    shared: { rating: "Medium" },
    unassigned: { rating: "Low" },
    "custom-1": { rating: "High" },
  },
  custom: [custom],
  legacy: [],
  domains: {
    x: ["a"],
    shared: ["a", "b"],
    unassigned: [],
    "custom-1": ["c"],
  },
  focus: [],
  actions: {},
  barriers: {},
  mission: { statement: "Manual mission", autoGenerated: false },
  act: {
    seed: "map-test",
    shortlist: [{ id: "kept", domainId: "a", what: "Keep shortlist", how: "Keep it" }],
    smartFocusId: "kept",
    domains: {
      a: { open: true, whatPage: 2, selectedWhat: "what-a", customWhat: "", howPage: 1, selectedHow: "how-a", customHow: "", actioned: "smart" },
    },
  },
};

const ranked = apps.rankedSelectedDomains(data, state);
assert.deepEqual(ranked.map((item) => item.displayPercent), [60, 30, 10]);
assert.equal(ranked.reduce((sum, item) => sum + item.displayPercent, 0), 100);

const map = apps.missionMapData(data, state, ranked);
assert.equal(map.center.label, "You");
assert.deepEqual(map.domains.map((domain) => domain.id), ["a", "b", "c"]);
assert.deepEqual(map.domains.map((domain) => domain.displayPercent), [60, 30, 10]);
assert.deepEqual(map.values.map((value) => value.id), ["custom-1", "x", "shared"]);
assert.equal(map.values.filter((value) => value.id === "shared").length, 1);
assert.deepEqual(map.values.find((value) => value.id === "shared").domainIds, ["a", "b"]);
assert.deepEqual(
  map.edges.filter((edge) => edge.target === "value-shared").map((edge) => edge.source),
  ["domain-a", "domain-b"],
);
assert.ok(map.edges.some((edge) => edge.source === "domain-a" && edge.target === "value-x"));
assert.ok(map.edges.some((edge) => edge.source === "domain-c" && edge.target === "value-custom-1"));
assert.ok(!map.edges.some((edge) => edge.source === "domain-b" && edge.target === "value-x"));
assert.ok(!map.values.some((value) => value.id === "unassigned"));

assert.ok(map.domains[0].radius > map.domains[1].radius);
assert.ok(map.domains[1].radius > map.domains[2].radius);
assert.equal(apps.domainPriorityRadius(0), 38);
assert.equal(apps.domainPriorityRadius(-20), 38);
assert.equal(apps.domainPriorityRadius(100), 78);

const zeroState = {
  ...state,
  assessments: {
    a: { current: 8, desired: 2 },
    b: { current: 5, desired: 5 },
    c: { current: 9, desired: 4 },
  },
};
const zeroMap = apps.missionMapData(data, zeroState);
assert.deepEqual(zeroMap.domains.map((domain) => domain.displayPercent), [0, 0, 0]);
assert.deepEqual(zeroMap.domains.map((domain) => domain.radius), [38, 38, 38]);

for (const mode of ["desktop", "mobile"]) {
  const first = apps.missionMapLayout(map, mode);
  const second = apps.missionMapLayout(apps.missionMapData(data, state), mode);
  assert.deepEqual(first, second, `${mode} layout must be deterministic`);
  assert.equal(first.domains.length, 3);
  assert.equal(first.values.length, 3);
}
assert.deepEqual(apps.missionMapData(data, state).edges, apps.missionMapData(data, state).edges);

const config = { toolId: "values", toolTitle: "Values", route: "/skill-finder/values/", schemaVersion: 1 };
const record = progress.makeRecord(config, state, new Date("2026-08-23T15:00:00Z"));
for (const serialized of [progress.serializeMarkdown(record, "# Values"), progress.serializeJson(record)]) {
  const restored = progress.parseProgress(serialized).record.state;
  assert.deepEqual(apps.missionMapData(data, restored), map, "saved source state must reproduce the same map");
}

const mission = apps.missionMarkup(data, structuredClone(state));
const order = [
  mission.indexOf(">Priorities</h4>"),
  mission.indexOf("values-priority-bar"),
  mission.indexOf("View calculation details"),
  mission.indexOf("My values map"),
  mission.indexOf(">Mission statement</h4>"),
];
assert.ok(order.every((index) => index >= 0));
assert.deepEqual(order, [...order].sort((left, right) => left - right));
assert.doesNotMatch(mission, /Priorities informing this draft|Your highest-priority directions/);
assert.match(mission, /<details class="values-calculation-details">\s*<summary>View calculation details<\/summary>/);
assert.doesNotMatch(mission, /<details class="values-calculation-details"[^>]*\sopen/);
for (const token of ["Current Score (1-10)", "Desired Score (1-10)", "Gap (desired - current)", "Raw Attention Score", "Relative Priority", "positive gap = max(desired - current, 0)", "High = 3/3", "attention score = positive gap × importance weight"]) {
  assert.ok(mission.includes(token), token);
}
assert.match(mission, /role="img" aria-labelledby="values-map-desktop-title values-map-desktop-description"/);
assert.match(mission, /data-values-map-fallback/);
assert.match(mission, /Shared Value — connected to Domain A, Full Canonical Name and Domain B &amp; Full Canonical Name/);

const actionData = {
  domains: {
    a: [{ id: "what-a", what: "A What", value_tags: ["Value X"], hows: [{ id: "how-a", text: "A How" }] }],
  },
  implementation_supports: [],
};
const actionState = structuredClone(state);
const shortlistBefore = structuredClone(actionState.act.shortlist);
const action = apps.actionDomainMarkup(data, actionData, actionState, ranked[0], true);
assert.match(action, /^<details class="values-action-domain"[^>]* open>/);
assert.match(action, /<details class="values-assigned-values"><summary>Values for this domain \(2\)<\/summary>/);
assert.doesNotMatch(action, /<details class="values-assigned-values"[^>]*\sopen/);
assert.match(action, /Value X/);
assert.match(action, /Shared Value/);
assert.match(action, /value="what-a"[^>]*checked/);
assert.match(action, /value="how-a"[^>]*checked/);
assert.equal(actionState.act.domains.a.whatPage, 2);
assert.equal(actionState.act.domains.a.howPage, 1);
assert.equal(actionState.act.domains.a.actioned, "smart");
assert.deepEqual(actionState.act.shortlist, shortlistBefore);

console.log("Values Mission map, calculation disclosure, and compact Act context checks passed");
