"use strict";

const assert = require("node:assert/strict");
const apps = require("../site/assets/skill-apps.js");
const progress = require("../site/assets/skill-progress.js");

const data = {
  domains: [
    { id: "a", name: "Domain A, Full Canonical Name" },
    { id: "b", name: "Domain B & Full Canonical Name" },
    { id: "c", name: "Domain C, Full Canonical Name" },
  ],
  values: [
    { id: "x", name: "Value X", definition: "", aliases: [] },
    { id: "shared", name: "Shared Value", definition: "", aliases: [] },
    { id: "unassigned", name: "Unassigned Value", definition: "", aliases: [] },
    { id: "ignored", name: "Ignored Value", definition: "", aliases: [] },
  ],
};
const custom = { id: "custom-1", name: "My custom Value", definition: "Mine", aliases: [] };
const state = {
  step: 4,
  furthestStep: 5,
  selectedDomains: ["a", "b", "c"],
  domainImportance: { a: "High", b: "High", c: "High" },
  assessments: {
    a: { current: 2, desired: 8 },
    b: { current: 3, desired: 6 },
    c: { current: 5, desired: 6 },
  },
  selected: {
    x: { rating: "High" },
    shared: { rating: "Medium" },
    unassigned: { rating: "Low" },
    "custom-1": { rating: "High" },
  },
  custom: [custom],
  legacy: [],
  domains: {
    x: ["a"],
    shared: ["a", "b"],
    unassigned: ["c"],
    "custom-1": ["c"],
  },
  focus: [],
  actions: {},
  barriers: {},
  mission: { statement: "Manual mission", autoGenerated: false },
  act: {
    seed: "map-test",
    shortlist: [{ id: "kept", domainId: "a", what: "Keep shortlist", how: "Keep it" }],
    smartFocusId: "kept",
    domains: {
      a: { open: true, whatPage: 2, selectedWhat: "what-a", customWhat: "", howPage: 1, selectedHow: "how-a", customHow: "", actioned: "smart" },
    },
  },
};

const ranked = apps.rankedSelectedDomains(data, state);
assert.deepEqual(ranked.map((item) => item.displayPercent), [60, 30, 10]);
assert.equal(ranked.reduce((sum, item) => sum + item.displayPercent, 0), 100);

const map = apps.missionMapData(data, state, ranked);
assert.equal(map.center.label, "You");
assert.deepEqual(map.domains.map((domain) => domain.id), ["a", "b", "c"]);
assert.deepEqual(map.domains.map((domain) => domain.displayPercent), [60, 30, 10]);
assert.deepEqual(map.values.map((value) => value.id), ["value-a-x", "value-a-shared", "value-b-shared", "value-c-custom-1", "value-c-unassigned"]);
assert.equal(map.values.filter((value) => value.valueId === "shared").length, 2);
assert.deepEqual(map.values.filter((value) => value.valueId === "shared").map((value) => value.domainId), ["a", "b"]);
assert.deepEqual(
  map.edges.filter((edge) => edge.target.endsWith("-shared")).map((edge) => edge.source),
  ["domain-a", "domain-b"],
);
assert.ok(map.edges.some((edge) => edge.source === "domain-a" && edge.target === "value-a-x"));
assert.ok(map.edges.some((edge) => edge.source === "domain-c" && edge.target === "value-c-custom-1"));
assert.ok(!map.edges.some((edge) => edge.source === "domain-b" && edge.target === "value-a-x"));
assert.ok(!map.values.some((value) => value.valueId === "ignored"));
assert.equal(Object.keys(state.selected).filter((id) => id === "shared").length, 1, "derived duplicate nodes must not duplicate source state");

const subsetState = {
  ...structuredClone(state),
  selectedDomains: ["a"],
  domainImportance: { a: "High" },
  assessments: { a: { current: 2, desired: 8 } },
  domains: { x: ["a"] },
};
const subsetMap = apps.missionMapData(data, subsetState);
assert.deepEqual(subsetMap.domains.map((domain) => domain.id), ["a", "b", "c"], "the fixed domain ring remains complete when only some domains are prioritized");
assert.deepEqual(subsetMap.domains.map((domain) => domain.displayPercent), [100, 0, 0]);
assert.deepEqual(subsetMap.domains.map((domain) => domain.ringIndex), [0, 1, 2]);

assert.ok(map.domains[0].radius > map.domains[1].radius);
assert.ok(map.domains[1].radius > map.domains[2].radius);
assert.equal(apps.domainPriorityRadius(0), 38);
assert.equal(apps.domainPriorityRadius(-20), 38);
assert.equal(apps.domainPriorityRadius(100), 78);

const zeroState = {
  ...state,
  assessments: {
    a: { current: 8, desired: 2 },
    b: { current: 5, desired: 5 },
    c: { current: 9, desired: 4 },
  },
};
const zeroMap = apps.missionMapData(data, zeroState);
assert.deepEqual(zeroMap.domains.map((domain) => domain.displayPercent), [0, 0, 0]);
assert.deepEqual(zeroMap.domains.map((domain) => domain.radius), [38, 38, 38]);

const initial = apps.missionMapVisibleGraph(map);
assert.deepEqual(initial.nodes.map((node) => node.id), ["you", "domain-a", "domain-b", "domain-c"]);
assert.equal(initial.nodes.filter((node) => node.type === "value").length, 0, "initial graph must contain no Value nodes");
assert.equal(initial.links.length, 3);
assert.equal(initial.nodes.find((node) => node.id === "you").targetX, 0);
assert.equal(initial.nodes.find((node) => node.id === "you").targetY, 0);
for (const domain of initial.nodes.filter((node) => node.type === "domain")) {
  assert.equal(domain.x, domain.targetX);
  assert.equal(domain.y, domain.targetY);
  assert.ok(Number.isFinite(domain.angle));
}
const compactInitial = apps.missionMapVisibleGraph(map, [], { compact: true });
assert.equal(compactInitial.nodes.filter((node) => node.type === "value").length, 0);
assert.ok(compactInitial.nodes.find((node) => node.id === "domain-a").radius > compactInitial.nodes.find((node) => node.id === "domain-b").radius);
assert.ok(compactInitial.nodes.find((node) => node.id === "domain-b").radius > compactInitial.nodes.find((node) => node.id === "domain-c").radius);
const domainAOpen = apps.missionMapVisibleGraph(map, ["a"]);
assert.deepEqual(domainAOpen.nodes.filter((node) => node.type === "value").map((node) => node.id), ["value-a-x", "value-a-shared"]);
assert.equal(apps.missionMapVisibleGraph(map, []).nodes.filter((node) => node.type === "value").length, 0, "a second toggle can restore the collapsed graph");
for (const value of domainAOpen.nodes.filter((node) => node.type === "value")) {
  const parent = domainAOpen.nodes.find((node) => node.domainId === value.domainId && node.type === "domain");
  assert.ok(Math.hypot(value.targetX - parent.targetX, value.targetY - parent.targetY) > 80, "values use local satellite targets around their own domain");
}
const domainsABOpen = apps.missionMapVisibleGraph(map, ["a", "b"]);
assert.deepEqual(domainsABOpen.nodes.filter((node) => node.type === "value" && node.valueId === "shared").map((node) => node.domainId), ["a", "b"]);
assert.equal(domainsABOpen.nodes.find((node) => node.id === "domain-a").expanded, true);
assert.equal(domainsABOpen.nodes.find((node) => node.id === "domain-b").expanded, true);
assert.equal(domainsABOpen.nodes.find((node) => node.id === "domain-c").expanded, false);
assert.deepEqual(apps.missionMapVisibleGraph(map, ["a", "b"]), apps.missionMapVisibleGraph(apps.missionMapData(data, state), ["a", "b"]), "derived starting positions must be deterministic");
assert.deepEqual(apps.missionMapData(data, state).edges, apps.missionMapData(data, state).edges);

assert.ok(apps.valueImportanceRadius("High") > apps.valueImportanceRadius("Medium"));
assert.ok(apps.valueImportanceRadius("Medium") > apps.valueImportanceRadius("Low"));
assert.ok(apps.valueImportanceDistance("High") < apps.valueImportanceDistance("Medium"));
assert.ok(apps.valueImportanceDistance("Medium") < apps.valueImportanceDistance("Low"));
assert.equal(map.values.find((value) => value.valueId === "x").radius, apps.valueImportanceRadius("High"));
const sharedRepresentations = map.values.filter((value) => value.valueId === "shared");
assert.ok(sharedRepresentations.every((value) => value.assignmentCount === 2));
assert.ok(sharedRepresentations.every((value) => value.radius > apps.valueImportanceRadius("Medium")), "multi-domain Values are visibly larger");
assert.equal(apps.valueVisualRadius("Medium", 1), apps.valueImportanceRadius("Medium"));
assert.ok(apps.valueVisualRadius("Medium", 2) > apps.valueVisualRadius("Medium", 1));
assert.ok(apps.valueVisualRadius("Medium", 3) > apps.valueVisualRadius("Medium", 2));
assert.equal(apps.valueVisualRadius("Medium", 99), apps.valueImportanceRadius("Medium") + 8, "multi-domain sizing is capped");
assert.equal(map.values.find((value) => value.valueId === "unassigned").linkDistance, apps.valueImportanceDistance("Low"));
const compactAll = apps.missionMapVisibleGraph(map, ["a", "c"], { compact: true });
assert.ok(compactAll.nodes.find((node) => node.valueId === "x").linkDistance < compactAll.nodes.find((node) => node.valueId === "unassigned").linkDistance);

const config = { toolId: "values", toolTitle: "Values", route: "/tool-finder/values/", schemaVersion: 1 };
const record = progress.makeRecord(config, state, new Date("2026-08-23T15:00:00Z"));
for (const serialized of [progress.serializeMarkdown(record, "# Values"), progress.serializeJson(record)]) {
  const restored = progress.parseProgress(serialized).record.state;
  assert.deepEqual(apps.missionMapData(data, restored), map, "saved source state must reproduce the same map");
  assert.ok(!("graph" in restored), "physics and camera data must not enter Values progress");
  assert.equal(restored.mission.statement, "Manual mission");
  assert.equal(restored.mission.autoGenerated, false);
}

const mission = apps.missionMarkup(data, structuredClone(state));
const order = [
  mission.indexOf(">Priorities</h4>"),
  mission.indexOf("values-priority-bar"),
  mission.indexOf("View calculation details"),
  mission.indexOf("My values map"),
  mission.indexOf(">Mission statement</h4>"),
];
assert.ok(order.every((index) => index >= 0));
assert.deepEqual(order, [...order].sort((left, right) => left - right));
assert.doesNotMatch(mission, /Priorities informing this draft|Your highest-priority directions/);
assert.match(mission, /<details class="values-calculation-details">\s*<summary>View calculation details<\/summary>/);
assert.doesNotMatch(mission, /<details class="values-calculation-details"[^>]*\sopen/);
for (const token of ["Current Score (1-10)", "Desired Score (1-10)", "Gap (desired - current)", "Raw Attention Score", "Relative Priority", "positive gap = max(desired - current, 0)", "High = 3/3", "attention score = positive gap × importance weight"]) {
  assert.ok(mission.includes(token), token);
}
assert.match(mission, /class="values-map-svg" role="group" aria-label="Interactive Values force graph/);
assert.match(mission, /data-values-map-fallback/);
assert.match(mission, /Domain A, Full Canonical Name — 60% Relative Priority[\s\S]*Shared Value — Medium importance/);
assert.match(mission, /Domain B &amp; Full Canonical Name — 30% Relative Priority[\s\S]*Shared Value — Medium importance/);
for (const action of ["zoom-out", "zoom-in", "fit", "reset"]) assert.match(mission, new RegExp(`data-graph-action="${action}"`));
assert.match(mission, /No Value nodes are visible/);

const actionData = {
  domains: {
    a: [{ id: "what-a", what: "A What", value_tags: ["Value X"], hows: [{ id: "how-a", text: "A How" }] }],
  },
  implementation_supports: [],
};
const actionState = structuredClone(state);
const shortlistBefore = structuredClone(actionState.act.shortlist);
const action = apps.actionDomainMarkup(data, actionData, actionState, ranked[0], true);
assert.match(action, /^<details class="values-action-domain"[^>]* open>/);
assert.match(action, /<details class="values-assigned-values"><summary>Values for this domain \(2\)<\/summary>/);
assert.doesNotMatch(action, /<details class="values-assigned-values"[^>]*\sopen/);
assert.match(action, /Value X/);
assert.match(action, /Shared Value/);
assert.match(action, /value="what-a"[^>]*checked/);
assert.match(action, /value="how-a"[^>]*checked/);
assert.match(action, /Schedule this action/);
assert.match(action, /data-action-calendar="a"/);
assert.equal(actionState.act.domains.a.whatPage, 2);
assert.equal(actionState.act.domains.a.howPage, 1);
assert.equal(actionState.act.domains.a.actioned, "smart");
assert.deepEqual(actionState.act.shortlist, shortlistBefore);

console.log("Values Mission map, calculation disclosure, and compact Act context checks passed");
