#!/usr/bin/env python3
"""Generate the Tool Finder topic sections from the canonical catalogue."""

from __future__ import annotations

import argparse
import html
import json
import re
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOGUE_PATH = ROOT / "site" / "data" / "tool-finder" / "catalogue.json"
OUTPUT_PATH = ROOT / "site" / "includes" / "tool-finder-topics.qmd"


def topic_slug(label: str) -> str:
    normalized = unicodedata.normalize("NFKD", label).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "-", normalized.lower()).strip("-")


def load_topics(path: Path = CATALOGUE_PATH) -> list[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    topics = data.get("topics")
    if not isinstance(topics, list) or not topics or not all(isinstance(topic, str) and topic.strip() for topic in topics):
        raise ValueError("Tool Finder catalogue topics must be a non-empty list of labels")
    if len(set(topics)) != len(topics):
        raise ValueError("Tool Finder catalogue topic labels must be unique")
    slugs = [topic_slug(topic) for topic in topics]
    if any(not slug for slug in slugs) or len(set(slugs)) != len(slugs):
        raise ValueError("Tool Finder catalogue topics must produce unique, non-empty anchors")
    return topics


def render_topics(topics: list[str]) -> str:
    lines = [
        "<!-- Generated by scripts/tool_finder_topics.py from site/data/tool-finder/catalogue.json. -->",
        "<!-- Do not edit this topic list by hand. -->",
        "",
    ]
    for topic in topics:
        escaped = html.escape(topic, quote=True)
        lines.extend(
            [
                f'::: {{.tool-finder-topic data-tool-finder-topic="{escaped}"}}',
                f"## {topic} {{#{topic_slug(topic)}}}",
                "",
                f'<div class="tool-finder-grid" data-tool-finder-cards="{escaped}" aria-live="polite"></div>',
                ":::",
                "",
            ]
        )
    return "\n".join(lines)


def expected_output() -> str:
    return render_topics(load_topics())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "validate"), nargs="?", default="generate")
    args = parser.parse_args()
    expected = expected_output()
    if args.command == "validate":
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit("Tool Finder topic include is stale; run python scripts/tool_finder_topics.py")
        print(f"Tool Finder topic include is current ({len(load_topics())} topics).")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} from the canonical catalogue.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
